### ISSUE TITLE
Подбор топиков для модели построенной с помощью пакета lda

### ISSUE THREAD

**Issue by Dementiy** [nikita-moor/ldatuning#1]
Не могу подобрать число топиков для модели построенной с помощью пакета lda (lda.collapsed.gibbs.sampler).
Формирую матрицу из документов и словаря с помощью ldaformat2dtm из пакета topicmodels:

```
dtm <- ldaformat2dtm(documents = documents, vocab = vocab)
result <- FindTopicsNumber(
  dtm,
  topics = seq(from = 2, to = 15, by = 1),
  metrics = c("Arun2010"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
```

Прошло больше 9 часов - без результатов. В чем может быт подводный камень?

**Comment by nikita-moor** [comment]
Насколько большой у вас корпус? Сколько времени занимает LDA разложение, если использовать непосредственно пакет topicmodels?

Например:
topicmodels:LDA(dtm, k = 10, method = "Gibbs", control = list(seed = 77))

Полный датасет AssociatedPress из примера (http://rpubs.com/siri/ldatuning) мой компьютер обрабатывает 10 часов. Возможно, ваш корпус достаточно большой. (Хотя в таком случае лимит в 15 топик будет маловат.)

P.S. Вы используете ldatuning в Linux или Windows? Хочу собрать статистику, потому что на Windows пакет очень мало тестировали.

**Comment by Dementiy** [comment]
Корпус состоит примерно из 6 тысяч документов (один документ это пост и комментарии к нему). LDA занимает примерно 14-15 минут в случае использования пакета `topicmodels` и столько же при использовании пакета `lda`. 

Я использую MacOS X, на Linux предполагаю результаты были теми же.

**Comment by nikita-moor** [comment]
У меня никаких идей. Если пришлёте данные, то могу проверить у себя. А так - копируйте код библиотеки (там всего один файл) и смотрите, что не так. Внутри самый обычный topicmodels, запущенный в несколько потоков. К сожалению, RStudio не позволяет использовать индикатор прогресса.

**Comment by Dementiy** [comment]
Я понял, что все-таки работает, но очень медленно (Core i5). Индикатор прогресса можно реализовать для однопоточных приложений (я его использую в своем пакете vkR), а вот для нескольких потоков не знаю как.
