### ISSUE TITLE
Typo in man page

### ISSUE THREAD

**Issue by sciatro** [nikita-moor/ldatuning#10]
[FindTopicNumber.Rd](https://github.com/nikita-moor/ldatuning/blob/master/man/FindTopicsNumber.Rd#L16) currently reads:

`\item{topics}{Vvector with number of topics to compare different models.}`

I think it should read:

`\item{topics}{Vector with number of topics to compare different models.}`

with one 'v' instead of two.

Thanks for the helpful package.

**Comment by nikita-moor** [comment]
Accepted. Fixed in the dev version, will be included into the next official release.

Thank you!
