### ISSUE TITLE
fit models...Error in checkForRemoteErrors(val) :    2 nodes produced errors; first error: invalid argument type

### ISSUE THREAD

**Issue by mdadkhah** [nikita-moor/ldatuning#11]
Hi,
I am going to use your interested library to find optimal number of topics for my data. I followed this tutorial: https://cran.r-project.org/web/packages/ldatuning/vignettes/topics.html and could receive answer.  but when i tried to use my owned data by using below code, i face with error.
I open my data via this code:
`dtm  <- read.csv("F:/Download/IoT App txt mining/Book2.txt")`

Then:

```
result <- FindTopicsNumber(
  dtm,
  topics = seq(from = 2, to = 15, by = 1),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
```

finally, i face with below error:

```
fit models...Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: invalid argument type
```
I am beginner in R. could you please help me?
Thank you!

**Comment by nikita-moor** [comment]
I think you should start from [simple model training](https://www.r-bloggers.com/getting-started-with-latent-dirichlet-allocation-using-rtexttools-topicmodels/), such as:
```r
library(topicmodels)
result <- LDA(
  AssociatedPress,  # put your data here
  k = 2,
  method = "Gibbs"
)
```
If it works correct, then move to the `ldatuning`.

Also, check does your `dtm` data format is similar to `AssociatedPress`.

**Comment by nikita-moor** [comment]
Your problem looks similar to #3, are you using Windows?

Try installing dev-version
```r
install.packages("devtools")
devtools::install_github("nikita-moor/ldatuning")
```

Sometimes windows users come with problems, but no one was patient enough to say does these patchs work or not.

**Comment by mdadkhah** [comment]
> 
> 
> Your problem looks similar to #3 & #9, are you using Windows?
> 
> Try installing dev-version
> 
> ```r
> install.packages("devtools")
> devtools::install_github("nikita-moor/ldatuning")
> ```
> 
> Sometimes windows users come with problems, but no one was patient enough to say does these patches work or not.

Thank you very much!
Yes, i use R on windows. When i created my document term matrix (dtm) with R, your tool worked for me with an error.  I could use metrics "Griffiths2004", "CaoJuan2009", "Deveaud2014" and see result. but "Arun2010" does not work for me. 
in other words, when i use below code, i face with error.
code
```
result <- FindTopicsNumber(
  doc_mat,
  topics = seq(from = 2, to = 10, by = 1),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
```
Error

```
fit models... done.
calculate metrics:
  Griffiths2004... done.
  CaoJuan2009... done.
  Arun2010...Error in FUN(X[[i]], ...) : 
  dims [product 2] do not match the length of object [3]
In addition: Warning message:
In cm1/cm2 :
  longer object length is not a multiple of shorter object length
```


But when i exclude "Arun2010" from code, it works.

code:

```
result <- FindTopicsNumber(
  doc_mat,
  topics = seq(from = 2, to = 10, by = 1),
  metrics = c("Griffiths2004", "CaoJuan2009", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
```

Result:

```
fit models... done.
calculate metrics:
  Griffiths2004... done.
  CaoJuan2009... done.
  Deveaud2014... done.
```

How can i correct error to have "Arun2010" in my analysis? 
Thank you!
