### ISSUE TITLE
Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: Each row of the input matrix needs to contain at least one non-zero entry

### ISSUE THREAD

**Issue by felipemorenoe** [nikita-moor/ldatuning#19]
Hello guys, 
Pretty inexperienced person here... 
I'm trying to usa ldatunning to find to find the optimal topic numbers for a database of facebook comments. 

I am running on: 
MacOSX 
R 4.0.2
Rstudio 1.3.1073

Everytime I try to run with my data: 
result <- FindTopicsNumber(
```
  dtm,
  topics = seq(from = 2, to = 15, by = 1),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
```
I get the error on the title 
I prepare my data with this: 

```
tokens = tolower(mensaje_lda$texto)
tokens = word_tokenizer(tokens)
it = itoken(tokens, ids = mensaje$parrafo, progressbar = FALSE)
v = create_vocabulary(it)
v = prune_vocabulary(v, term_count_min = 10, doc_proportion_max = 0.5, doc_proportion_min = 0.001)
vectorizer = vocab_vectorizer(v)
dtm = create_dtm(it, vectorizer, type = "dgCMatrix")
```
I am following this guide https://cran.r-project.org/web/packages/ldatuning/vignettes/topics.html

and when I try the FindTopicsNumber on the Associated_press data it actually runs... what am I doing wrong? any help would be appreciated.

**Comment by titaniumtroop** [comment]
You are generating the `dtm` with `text2vec` functions, and this package was designed to work with `topicmodels`-based `dtm`s. You may be able to convert the `dtm` from `text2vec` to `topicmodels` using the `as.simple_triplet_matrix` function from the `slam` package as described in [this SO post](https://stackoverflow.com/questions/46788242/can-text2vec-and-topicmodels-generate-similar-topics-with-suitable-parameter-set), but I haven't tried it. If you get it to work, perhaps you could post your code and we can incorporate a check to convert a `text2vec` `dtm` for use with this package?

**Comment by felipemorenoe** [comment]
Thank you, will see if I can do that, otherwise I will just redo the data process with topicmodels
