### ISSUE TITLE
Error in checkForRemoteErrors(val) :  2 nodes produced errors; first error: there is no package called 'topicmodels'

### ISSUE THREAD

**Issue by rdatasculptor** [nikita-moor/ldatuning#3]
I got the same error mentioned [here](http://stackoverflow.com/questions/37945931/cant-run-ldatuning-package-in-r)

Is this a bug or is it something we did wrong in our code?

**Comment by nikita-moor** [comment]
I tested the package only on win-builder, it was successful. I'll try to find a machine with Windows and check it.

**Comment by rdatasculptor** [comment]
Thanks!

**Comment by nikita-moor** [comment]
I just have finished test on the windows machine:
* Windows XP
* R 3.3.2
* ldatuning 0.2.0

Result is correct. The only one message I received was from Windows firewall, it asked me to grand network access for R. May be it is the source of the problem?

**Comment by nikita-moor** [comment]
@rdatasculptor can you trace function code to find the error?
Place cursor on the function name "FindTopicNumber", press F2 and run internal instructions of the function one-by-one.

P.S. Firewall does not affect R.

**Comment by rdatasculptor** [comment]
It stops with this peace of code:

```
models <- parallel::parLapply(X = topics, fun = function(x) {
    topicmodels::LDA(dtm, k = x, method = method, control = control)
  })
```

**Comment by rdatasculptor** [comment]
Thanks! I wanted to test it, but there went something wrong (namespace errors in my library) when installing it from github. What's the best way to test it?

**Comment by nikita-moor** [comment]
It seems as libraries collision. Can you clean reinstall R? If you use RStudio, you can create new project and activate Packrat to build local repository with base packages only, and install ldatuning-dev there.

**Comment by nikita-moor** [comment]
I have no idea. You can copy the ldatuning code into your own file and use it with directly.
https://github.com/nikita-moor/ldatuning/blob/master/R/main.R

**Comment by rdatasculptor** [comment]
That worked! Thanks for the help
To make it work as planned I had to put a library path within this piece of code, right before the LDA call:

```
models <- parallel::parLapply(X = topics, fun = function(x) {
.libPaths(...)
    # topicmodels::LDA(dtm, k = x, method = method, control = control)
    LDA(dtm, k = x, method = method, control = control)
  })
```

**Comment by nikita-moor** [comment]
I'm glad that it works for you. I leave this issue open, because I'm not sure is it general Windows behavior or your computer's specific.

Thank you for your bug report.

**Comment by malletnewbie** [comment]
I am new to Topic Modeling and R and tried to run this code but I get the same error.
However, I tried to fix it as you mentioned it but I didn't succeed.
Can you tell me what I have to put in the brackets at .libPaths(...)?
Do I have to change anything else in the original code or do I have to run it before I initialize my own corpus at the end of this file?
I hope you understand my problems...
Thanks in advance!

**Comment by nikita-moor** [comment]
I add libPath command into the code. Please, try dev version:
```
install.packages("devtools")
devtools::install_github("nikita-moor/ldatuning")
```
Now, call the `FindTopicsNumber` function with new parameter `libpath`. I can't reproduce the issue, but I guess it should be:
```
FindTopicsNumber(
  ...
  libpath = "C:/Program Files/R/R-2.15.2/library"
)
```
