### ISSUE TITLE
error in ploting gibbs analysis result. is this message right.

### ISSUE THREAD

**Issue by Atiq310** [nikita-moor/ldatuning#33]
FindTopicsNumber_plot(result)
Warning: The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the ldatuning package.
  Please report the issue at <https://github.com/nikita-moor/ldatuning/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by nikita-moor** [comment]
Duplicate #32
