### ISSUE TITLE
Error: "Each row of the input matrix needs to contain at least one non-zero entry"

### ISSUE THREAD

**Issue by ielbert** [nikita-moor/ldatuning#6]
I'm getting this error when trying to run ldatuning:
fit models...Error in checkForRemoteErrors(val) :
  4 nodes produced errors; first error: Each row of the input matrix needs to contain at least one non-zero entry
Calls: FindTopicsNumber ... clusterApply -> staticClusterApply -> checkForRemoteErrors

My corpus is pretty sparse but I'm able to feed it to lda and topicmodel packages without any issues:
<<VCorpus>>
Metadata:  corpus specific: 0, document level (indexed): 0
Content:  documents: 60000
<<DocumentTermMatrix (documents: 60000, terms: 176674)>>
Non-/sparse entries: 3072914/10597367086
Sparsity           : 100%
Maximal term length: 30
Weighting          : term frequency (tf)

**Comment by nikita-moor** [comment]
I have no idea how to reproduce the problem. Can you share the dataset?

**Comment by frimane** [comment]
You have the sum of the frequencies of words in some Documents equal to zero; try to add these lines to eliminate the documents that sum to zero ; 
rowSum <- apply(documents , 1, sum) 
documents   <- documents[rowSum> 0, ]

**Comment by VINEET-KAUSHIK** [comment]
@frimane I think this will remove documents and LDA can't be applied then?
