### ISSUE TITLE
Error in seq_len(m) : argument must be coercible to non-negative integer

### ISSUE THREAD

**Issue by amitagrey** [nikita-moor/ldatuning#8]
I am getting following errors after running the code as given in the vignette

library(pacman)
p_load("tm", "SnowballCC", "RColorBrewer", "ggplot2", "wordcloud", "biclust", 
       "cluster", "igraph", "fpc", "Rcampdf")
p_load("topicmodels", "devtools", "ldatuning")
data("AssociatedPress", package="topicmodels")
dtm <- AssociatedPress[1:10, ]
result <- FindTopicsNumber(
  dtm,
  topics = seq(from = 2, to = 15, by = 1),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
**knitr::kable(result)**
**Error in seq_len(m) : argument must be coercible to non-negative integer
In addition: Warning messages:
1: In rep(digits, length.out = m) :
  first element used of 'length.out' argument
2: In seq_len(m) : first element used of 'length.out' argument**

**FindTopicsNumber_plot(result)**
**Error in subset.default(values, select = 2:ncol(values)) : 
  argument "subset" is missing, with no default``**

**Comment by titaniumtroop** [comment]
The packages listed in the first `p_load` call aren't necessary to run the call to `FindTopicsNumber`. I cannot recreate the error. I get the following result:

```
library(pacman)
p_load("topicmodels", "devtools", "ldatuning")
data("AssociatedPress", package="topicmodels")
dtm <- AssociatedPress[1:10, ]
result <- FindTopicsNumber(
  dtm,
  topics = seq(from = 2, to = 15, by = 1),
  metrics = c("Griffiths2004", "CaoJuan2009", "Arun2010", "Deveaud2014"),
  method = "Gibbs",
  control = list(seed = 77),
  mc.cores = 2L,
  verbose = TRUE
)
result

   topics Griffiths2004 CaoJuan2009 Arun2010 Deveaud2014
1      15     -15297.82   0.5047240 15.92711   0.1362596
2      14     -15338.24   0.4927860 15.36552   0.1406462
3      13     -15319.82   0.4944709 15.80569   0.1504368
4      12     -15326.94   0.4756351 15.81278   0.1594651
5      11     -15293.55   0.4347111 15.23313   0.1770861
6      10     -15291.00   0.3829542 14.93706   0.1969989
7       9     -15303.87   0.3379840 14.71664   0.2181424
8       8     -15256.30   0.3061726 14.78140   0.2435689
9       7     -15259.80   0.2746812 14.82908   0.2746203
10      6     -15251.04   0.2612029 15.28425   0.3101625
11      5     -15226.91   0.1875260 15.34470   0.3718687
12      4     -15242.86   0.1779016 16.29708   0.4323482
13      3     -15266.66   0.1600736 16.97832   0.5318997
14      2     -15349.79   0.1169522 18.47430   0.6989189
```

Please let me know if this issue can be closed.
